#server.port=80
#server.context-path=/demo

server:
  port: 80
  servlet:
    context-path: /demo
    
    
#database 설정
#1.설정 파일에 수행 - 독고다이로 돌아가는 프로젝트에서 유용
#2.설정 클래스 생성(@configuration)

spring:  datasource:    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: kh
    password: kh
    dbcp2:
     max-total: 20
     max-idle: 10
     max-wait-millis: 3000
     
     
#jpa 설정
  jpa:    database: oracle
    show-sql: true
    hibernate:      ddl-auto: create # create 면 시작시 생성, update 면 변동사항 갱신. 
     
# swagger 정적 자원 설정
#  mvc:#    static-path-pattern: /swagger-ui.html